### ISSUE TITLE
In deployments,  /KuduLite throw out  System.IO.IOException: The process cannot access the file

### ISSUE THREAD

**Issue by shengdamao** [Azure-App-Service/KuduLite#124]
ILB-ASE Function App. 
Use devops to deploy. SCM Type VSTSRM.

Symptoms:
Deployments logs showed status "succeed" but files remained unchanged.  07-03
Found this exception during this deployments. 

Afterwards, when deployments are without this exception, deployments are all healthy.  07-05  to 07-09

We have disabled the kudulite from setting currently. 
Is this exception caused by Kudulite? 
If it is, is there anyway not using KuduLite as the default option except adding the setting.

Open() at /tmp/KuduLite/Kudu.Core/Deployment/DeploymentStatusFile.cs:75 System.IO.IOException: The process cannot access the file '/home/site/deployments/1633388cead3453a9d77be9e75c3704d/status.xml' because it is being used by another process.
    at System.IO.FileStream.Init(FileMode mode, FileShare share)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at System.IO.Abstractions.FileWrapper.OpenRead(String path)
    at Kudu.Core.Deployment.DeploymentStatusFile.<>c__DisplayClass6_0.<Open>b__0() in /tmp/KuduLite/Kudu.Core/Deployment/DeploymentStatusFile.cs:line 82

**Comment by sanchitmehta** [comment]
Thanks for reporting this @shengdamao. This happens due to latency in NFS Volume that app service uses. We have added more resiliency to deployment codepaths in PR: #141 . This should retry in case the file is busy.
