### ISSUE TITLE
POST /api/zipdeploy failing with "Missing content-type boundary"

### ISSUE THREAD

**Issue by jeffnicholson-arcurve** [Azure-App-Service/KuduLite#70]
zipdeploy via `POST /api/zipdeploy` to a Linux App Service is failing, error is related to "Missing content-type boundary".  
This was working as of yesterday (16-07-2019).  
Relevant snip of stack trace (full trace below):  
```
Error occurred, type: error, text: Missing content-type boundary., stackTrace:    at Kudu.Services.MultipartRequestHelper.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit) in /tmp/KuduLite/Kudu.Services/Util/MultipartRequestHelper.cs:line 17
   at Kudu.Services.FileStreamingHelper.StreamFile(HttpRequest request, Stream targetStream) in /tmp/KuduLite/Kudu.Services/Util/FileStreamingHelper.cs:line 29
   at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ZipDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 225
   at Kudu.Services.Deployment.PushDeploymentController.ZipPushDeploy(Boolean isAsync, String author, String authorEmail, String deployer, String message) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 94
```

### Repro
With PowerShell, follow Example 2 from https://github.com/projectkudu/kudu/wiki/REST-API#sample-of-using-rest-api-with-powershell:
```
$username = "`$website"
$password = "pwd"
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username, $password)))
$userAgent = "powershell/1.0"

# Example 2: call the zipdeploy API (which uses POST)
$apiUrl = "https://{sitename}.scm.azurewebsites.net/api/zipdeploy"
$filePath = "C:\Temp\foo.zip"
Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method POST -InFile $filePath -ContentType "multipart/form-data"
```
The zip file is a packaged web app, which was previously deployed successfully via zipdeploy.

### Error
Request fails with a `500`:
`Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.`

The kudu trace logs show an exception:
```
2019-07-17T13:26:49  Startup Request, url: /api/zipdeploy, method: POST, type: request, pid: 72,1,4, ScmType: None
2019-07-17T13:26:51    Error occurred, type: error, text: Missing content-type boundary., stackTrace:    at Kudu.Services.MultipartRequestHelper.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit) in /tmp/KuduLite/Kudu.Services/Util/MultipartRequestHelper.cs:line 17
   at Kudu.Services.FileStreamingHelper.StreamFile(HttpRequest request, Stream targetStream) in /tmp/KuduLite/Kudu.Services/Util/FileStreamingHelper.cs:line 29
   at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ZipDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 225
   at Kudu.Services.Deployment.PushDeploymentController.ZipPushDeploy(Boolean isAsync, String author, String authorEmail, String deployer, String message) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 53
2019-07-17T13:26:51      Error occurred, type: error, text: Missing content-type boundary., stackTrace:    at Microsoft.AspNetCore.Http.Features.FormFeature.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 53
```

**Comment by sanchitmehta** [comment]
We will investigate this problem. @jeffnicholson-arcurve Which run time stack are you using ? We recently enabled KuduLite for certain stacks on App Service on Linux, this might be a migration problem from Kudu to KuduLite.

**Comment by jeffnicholson-arcurve** [comment]
Thanks @sanchitmehta. We're using App Service on Linux.

**Comment by jeffnicholson-arcurve** [comment]
To be more specific, it's .NET Core 2.1

**Comment by jeffnicholson-arcurve** [comment]
@sanchitmehta Any more details on this? Is it an issue, or is it something I'm doing incorrectly on my end? Do I need to pursue another method of deploying?
Any update would be appreciated.

**Comment by PeterHexDahl** [comment]
This is affecting us as well, one solution i was given by microsoft support was disabeling kudu lite in application settings.

ENABLE_KUDU_LITE = false.

**Comment by jeffnicholson-arcurve** [comment]
@PeterHexDahl that worked, thanks very much, really appreciate it.

**Comment by sanchitmehta** [comment]
@jeffnicholson-arcurve  @PeterHexDahl we will completely migrate to KuduLite for App Service on Linux in future. Sorry about the late reply.

I tested; the problem is KuduLite expects a multipart/form-data boundary; which is not provided by the powershell.

You could either change the content-type to "content/zip" if you want to **use Powershell**

```
$sitename='site1' # if you site is site1.azurewebsites.net
$username='$site1' # Example: $username='$site1' (NOT 'site1\$site1', NOT 'site1\site1'. Also, note the single quotes.)
$password='password'
$zipFilePath='E:\zipFilePath.zip'

$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username, $password)))
$apiUrl = "http://localhost:7397/api/zipdeploy"
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method POST -InFile $zipFilePath -ContentType "context/zip"
```

**or use curl**

1. Octet Stream: `curl -X POST -u <user> https://{sitename}.scm.azurewebsites.net/api/zipdeploy -T <zipfile> `
2. Multipart/form-data : `curl -v -F 'upload=@\"<zipfile>\"  https://{sitename}.scm.azurewebsites.net/api/zipdeploy`

**Comment by jeffnicholson-arcurve** [comment]
Thanks for the reply and the alternative approaches.
I understand what the issue is, however I don't see how you can close this by just providing a work around.
Clearly the behavior between Kudu and KuduLite differs here. If you force migration and do not maintain the same behavior you will potentially break people.
I happened to run into this issue as I was actively working on my deployment pipeline. What happens to a team that has a pipeline that was working, then you migrate them (with no notice) to KuduLite and suddenly all their deployments are broken?
